### ISSUE TITLE
how can I ignore the SSL verification?

### ISSUE THREAD

**Issue by nadobando** [inversoft/barista#1]
Hi, 
I'm trying to integrate chef queries with jenkins and found this repo, I have tried to use this library but I';
I need to ignore the SSL verification becasuse we are using a self signed certificate in a local environment, how can I achieve this?

Thanks in advance, 
Nadir.

**Comment by robotdan** [comment]
Generally speaking you can add your self signed certificate to the Java Keystore in this scenario to indicate this is a trusted certificate using the `$ keytool -import` command. 

Have you tried this approach?

**Comment by peavers** [comment]
I'd also like the ability to ignore SSL verification.

**Comment by robotdan** [comment]
Have you tried using Keytool as mentioned above to add your certificate to the keystore? 

As far as I know, all of the SSL verification is handled by the `java.net` API, under the hoods this is just using an `HttpURLConnection`.  When using `https`, we'll try to set up an SSL Socket and doing so will validate the certificate authority.

**Comment by peavers** [comment]
You're correct, I just disabled verification for the request (dev environment) using https://gist.github.com/peavers/169d8d6e42188b2824ffcbf2f2f029f4

**Comment by robotdan** [comment]
Thanks @peavers and @nadobando  for reporting. Added this feature.
`client. disableSSLValidation()` and `client. enableSSLValidation()`.

**Comment by robotdan** [comment]
Fixed in version `0.5.0`.
