### ISSUE TITLE
attributes always comes back as null

### ISSUE THREAD

**Issue by peavers** [inversoft/barista#2]
I can't seem to get back any attributes, ideally the FQDN of the node, everything else is populated however.

**Comment by robotdan** [comment]
I don't know that the FQDN is part of the Chef Node object.  
https://www.rubydoc.info/gems/chef/Chef/Node#attributes-instance_method

Is the FQDN an attribute you have added to your node?  Can you verify if the FQDN comes back in a JSON response w/out using the ChefClient ?

**Comment by peavers** [comment]
Hmm I was looking at https://docs.chef.io/attributes.html

**Comment by robotdan** [comment]
Thanks @peavers! Looks like this was just a bug on my end. I tested this fix, and I can now see attributes, and I can retrieve the `fqdn`. 

 I'm going to see if I can get a fix in for issue #1 as well before I release.

**Comment by robotdan** [comment]
Fixed in version `0.5.0`.
