### ISSUE TITLE
Bug in delete client method

### ISSUE THREAD

**Issue by Dharanir31** [inversoft/barista#5]
api is GET /organizations/NAME/clients 

It should be  urlSegment("clients")  not nodes urlSegment("nodes")

 public ClientResponse<Void, Void> deleteClient(String name) {
    return start(client ->
        client.urlSegment("organizations")
              .urlSegment(organization)
              .urlSegment("nodes")
              .urlSegment(name)
              .delete());
  }
              
Also can you add method for retrieve clients  and retrieve cookbooks. https://docs.chef.io/api_chef_server.html#id28

GET /organizations/NAME/clients
GET /organizations/NAME/cookbooks

**Comment by robotdan** [comment]
Thanks for reporting. It looks like `deleteClient` and `deleteNode` are swapped. We are using this in prod, so perhaps that is why I hadn't noticed since we always call both anyway. 

I'll fix and look at adding those methods.

**Comment by robotdan** [comment]
Fixed, and new methods are available in version 0.6.0. Let me know if it works ok for you.
